export const MAX_MESSAGES = 20;
export const MAX_REQUEST_MESSAGES = 100;
export const MAX_MESSAGE_LENGTH = 20000;
export const LLM_TIMEOUT_MS = 60000;

export const RATE_LIMIT_MAX = 20;
export const RATE_LIMIT_WINDOW_MS = 60 * 1000;

export const CLASSIFIER_TIMEOUT_MS = 2500;
export const CLASSIFIER_MAX_TOKENS = 8;

export const DEFAULT_ANSWER_CACHE_TTL_MS = 24 * 60 * 60 * 1000;
export const DEFAULT_ANSWER_CACHE_MAX_ENTRIES = 500;

export const SCHEDULE_CACHE_TTL_MINUTES = 10;
export const SCHEDULE_FALLBACK_TTL_HOURS = 24;
